# core/security/signature_checker.py

"""
Signature Checker — HMAC-based request integrity validation.

This module is optional but strongly recommended for:
 - Redirect server → Bot callback authenticity
 - Preventing forged / modified verification tokens
 - Verifying that incoming requests were generated by YOUR system

Uses a shared secret key stored in:
    config.TOKEN_SECRET

Supported:
 - generate_signature(data) → returns hex HMAC signature
 - verify_signature(data, signature) → True/False
"""

import hmac
import hashlib
from typing import Union
from core.config import config


class SignatureChecker:
    SECRET = config.TOKEN_SECRET.encode()  # ensure bytes

    # --------------------------------------------------------------------
    # GENERATE SIGNATURE (HMAC-SHA256)
    # --------------------------------------------------------------------
    @staticmethod
    def generate_signature(data: Union[str, bytes]) -> str:
        """
        Generates an HMAC-SHA256 signature for the given data.

        Args:
            data: string or bytes to sign.

        Returns:
            Hex digest string (64 chars).
        """
        if isinstance(data, str):
            data = data.encode()

        signature = hmac.new(
            SignatureChecker.SECRET,
            msg=data,
            digestmod=hashlib.sha256
        ).hexdigest()

        return signature

    # --------------------------------------------------------------------
    # VERIFY SIGNATURE (CONSTANT TIME COMPARISON)
    # --------------------------------------------------------------------
    @staticmethod
    def verify_signature(data: Union[str, bytes], signature: str) -> bool:
        """
        Validates that the signature matches the given data.

        Args:
            data: original string or bytes
            signature: incoming HMAC hex digest

        Returns:
            True if signature matches, False otherwise.
        """
        if isinstance(data, str):
            data = data.encode()

        expected = SignatureChecker.generate_signature(data)
        return hmac.compare_digest(expected, signature)

    # --------------------------------------------------------------------
    # SAFE PAYLOAD + SIGNATURE COMBO (PREFIXED)
    # --------------------------------------------------------------------
    @staticmethod
    def pack(data: str) -> str:
        """
        Combine data + signature into a single safe packet:
            <data>::<signature>

        Useful for passing through redirect URLs.
        """
        sig = SignatureChecker.generate_signature(data)
        return f"{data}::{sig}"

    @staticmethod
    def unpack(packet: str):
        """
        Extracts (data, signature) from 'data::signature'.

        Returns:
            (data, signature) or (None, None) on error.
        """
        if "::" not in packet:
            return None, None

        try:
            data, sig = packet.rsplit("::", 1)
            return data, sig
        except:
            return None, None

    @staticmethod
    def unpack_and_verify(packet: str) -> str:
        """
        Extracts and verifies the packet.
        Returns:
            data string if signature valid,
            None otherwise.
        """
        data, sig = SignatureChecker.unpack(packet)
        if not data or not sig:
            return None

        if SignatureChecker.verify_signature(data, sig):
            return data

        return None
